Repository carrawao/SWE_Finanzen, pull requests merged in 2022-05, with the labels that each got.

#40 Update Search Functions
  Backend/package-lock.json
  Backend/package.json
  Backend/routes/Generals/search.js
  Backend/routes/Generals/searchCrypto.js
  Backend/routes/Generals/searchShare.js
Labels: enhancement

#46 Backend
  Backend/Dockerfile
  Backend/readme.md
  Backend/routes/Activities/getCryptoDataFromDateForActivities.js
  Backend/routes/Activities/getShareDataFromDateForActivities.js
  Backend/routes/routes.js
Labels: enhancement

#47 feature/watchlist: fixing all tests
  Frontend/src/components/screens/Analysis/AnalysisDetailitem.jsx
  Frontend/src/components/screens/Analysis/AnalysisList.jsx
  Frontend/src/components/screens/Analysis/AnalysisScreen.jsx
  Frontend/src/components/screens/Analysis/__test__/AnalysisScreen.test.jsx
  Frontend/src/components/screens/Analysis/__test__/__snapshots__/AnalysisScreen.test.jsx.snap
  Frontend/src/components/screens/AssetDetails/AssetDetailsScreen.jsx
  Frontend/src/components/screens/AssetDetails/ChartButtons.jsx
  Frontend/src/components/screens/AssetDetails/Masterdata.jsx
  Frontend/src/components/screens/AssetDetails/Stockchart.jsx
  Frontend/src/components/screens/AssetDetails/StockchartCard.jsx
  Frontend/src/components/screens/AssetDetails/__test__/AssetDetails.test.jsx
  Frontend/src/components/screens/AssetDetails/__test__/__snapshots__/AssetDetails.test.jsx.snap
  Frontend/src/components/screens/Dashboard/AllocationGraph.jsx
  Frontend/src/components/screens/Dashboard/DashboardScreen.jsx
  Frontend/src/components/screens/Dashboard/__test__/DashboardScreen.test.jsx
  Frontend/src/components/screens/Dashboard/__test__/__snapshots__/DashboardScreen.test.jsx.snap
Labels: bug

#66 Feature/activities
  Frontend/src/components/screens/Activities/ActivitiesList.jsx
  Frontend/src/components/screens/Activities/ActivitiesScreen.jsx
  Frontend/src/components/screens/Activities/AddActivity/AddActivityForm.jsx
  Frontend/src/components/screens/Activities/AddActivity/AddActivityScreen.jsx
  Frontend/src/components/screens/Activities/AddActivity/SearchAssetsInput.jsx
  Frontend/src/components/screens/Analysis/__test__/__snapshots__/AnalysisScreen.test.jsx.snap
  Frontend/src/components/screens/Settings/SettingsScreen.jsx
  Frontend/src/routes/index.jsx
  Frontend/src/services/DailyDataArraysService.js
  Frontend/src/services/FindDependsOnService.js
  Frontend/src/services/SortActivitiesService.js
  Frontend/src/services/UpdateBuysArrayService.js
  Frontend/src/services/UpdateDepositsArrayService.js
  Frontend/src/services/UpdateStateChangesService.js
  Frontend/src/services/index.jsx
Labels: bug, enhancement
